# Generated by Django 2.2.1 on 2019-05-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190517_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='red_num',
            field=models.IntegerField(default=0),
        ),
    ]
