# Generated by Django 2.2.1 on 2019-05-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_red_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='red_num',
            new_name='read_num',
        ),
    ]
