# Generated by Django 2.2.1 on 2019-05-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190517_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
